---
title: "analysis"
author: "Patrick"
date: "2023-07-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(RSocrata)
library(tigris)
library(sf)
library(leaflet)
library(htmltools)
library(gt)
library(janitor)

```


```{r}
scooter_trips <- read.socrata("https://data.cityofchicago.org/resource/2i5w-ykuw.csv")

scooter_trips_tract <- read.socrata("https://data.cityofchicago.org/resource/cini-k95q.csv")

equity_priority_area <- read.socrata("https://data.cityofchicago.org/resource/99tm-6k6i.csv") %>% 
  st_as_sf(wkt = "polygon") %>% 
  st_union()
```

Number of scooter trips over time
```{r}

scooter_trips_clean <- scooter_trips %>% 
  mutate(date = floor_date(start_time, "month"))

scooter_trips_sum <- scooter_trips_clean %>% 
  group_by(date) %>% 
  summarize(trips = n())


```

```{r}
ggplot(scooter_trips_sum)+
  geom_line(mapping = aes(x = as.Date(date), y = trips))+
  scale_x_date(date_labels = "%m-%Y")+
  scale_y_continuous(label = scales::comma)
```


census data
```{r}

tracts_sf <- tracts(
  state = "IL",
  county = "Cook",
  cb = T
)


```
Just 18% of rides in the equity zones
```{r}

scooter_trips_sf <- scooter_trips %>% 
  filter(!is.na(start_centroid_longitude)) %>% 
  st_as_sf(coords = c("start_centroid_longitude", "start_centroid_latitude"), remove = F)

scooter_trips_equity <- scooter_trips_sf %>% 
  mutate(equity_zone = lengths(st_intersects(.,equity_priority_area)))

scooter_trips_equity %>% as.data.frame() %>% 
  group_by(equity_zone == 1, vendor == "Lyft") %>% 
  summarize(n = n())
```

```{r}

scooter_trips_tract_sf <- scooter_trips_tract %>% 
  mutate(GEOID = as.character(start_census_tract)) %>% 
  left_join(tracts_sf, by = "GEOID") %>% 
  st_as_sf()

scooter_tract_sum <- scooter_trips_tract_sf %>% 
  group_by(GEOID) %>% 
  summarize(trips = sum(trip_count, na.rm = T)) %>% 
  filter(!is.na(GEOID))

scooter_tract_nolyft <- scooter_trips_sf %>% 
  filter(vendor != "Lyft") %>% 
  st_intersection(scooter_trips_tract_sf) %>% 
  group_by(GEOID) %>% 
  summarize(no_lyft_rides = n())

```



Map of scooter trips
```{r}
ggplot(scooter_tract_sum)+
  geom_sf(mapping = aes(fill = trips))

#mapview::mapview(scooter_tract_sum)

tag.map.title <- tags$style(HTML("
  .leaflet-control.map-title {
    position: fixed !important;
    padding: 10px;
    background: rgba(255,255,255,0.8);
    color: black;
    border-radius: 5px;
  }
  .title {
    padding: 0px;
    margin: 0px;
    font-size: 20px;
    margin-block: 0px;
    font-weight: 800;
  }"))

title <- tags$div(
  tag.map.title, HTML("<p class = 'title'>The huge majority of E-Scooter Rides don't happen in the Equity Zone</p>")
)  

pal <- colorNumeric(
  palette = "Greens",
  domain = scooter_tract_sum$trips)

no_lyft_pal <- colorNumeric(
  palette = "Greens",
  domain = scooter_tract_sum$trips)

map <- leaflet(scooter_tract_sum) %>% 
  addProviderTiles(provider = "CartoDB.Positron") %>% 
  addPolygons(color = ~pal(trips),
              opacity = 0.9,
              weight = 0.5) %>% 
  addPolygons(data = no_lyft,
              color = ~no_lyft_pal,
              opacity = 0.9,
              weight = 0.5) %>% 
  addPolygons(data = equity_priority_area,
              color = "red",
              weight = 0.5,
              opacity = 0.5,
              layerId = "equity") %>% 
  addLegend("bottomright", pal = pal, values = ~trips,
    title = "Rides 5/2022-12/2022",
    opacity = 1
  ) %>% 
  addLegend("topright", group = "equity", colors = "red", labels = "equity zone") %>% 
  addControl(title,
             className = "map-title",
             position = "topleft")

map

mapview::mapshot(map, "map.html")
```




Differences in vendors?
Are some scooters higher quality because they are not distributed evenly between neighborhoods?
```{r}

count(scooter_trips_equity %>% as.data.frame() %>% group_by(vendor), equity_zone) %>% 
  pivot_wider(names_from = "equity_zone", values_from = "n") %>% 
  adorn_totals("col") %>% 
  mutate(percent_equity_zone = scales::percent(`1`/(`0`+`1`)))
  
count(scooter_trips_clean, vendor) %>% 
  adorn_totals() %>% 
  adorn_percentages("col")
```
Lyft only
```{r}
lyft_only <- scooter_trips_equity %>%
  filter(vendor == "Lyft") %>% 
  group_by(start_centroid_latitude, start_centroid_longitude) %>% 
  summarize(count = n()) %>% 
  arrange(count)

divvy_stations <- read.socrata("https://data.cityofchicago.org/resource/bk89-9dk7.json") %>% 
  st_as_sf(coords = c("location.longitude", "location.latitude"))

leaflet(lyft_only) %>% 
  addProviderTiles(provider = "CartoDB.Positron") %>% 
  addCircleMarkers(color = "pink",
              fillOpacity = 0.9,
              radius = ~sqrt(count)/10) %>% 
  addMarkers(lng = lyft_only$start_centroid_longitude,
             lat = lyft_only$start_centroid_latitude)
```



trips but desitnation
```{r}

end_scooter_trips_sf <- scooter_trips %>% 
  filter(!is.na(end_centroid_longitude)) %>% 
  st_as_sf(coords = c("end_centroid_longitude", "end_centroid_latitude"), remove = F)

end_scooter_trips_equity <- end_scooter_trips_sf %>% 
  mutate(equity_zone = lengths(st_intersects(.,equity_priority_area)))

count(end_scooter_trips_equity %>% as.data.frame(), equity_zone == 1) %>% 
  janitor::adorn_percentages("col")

```

```{r}
twenty20 <- 540035/122
twenty19 <- 664975/122
program <- 6300

```

